### ISSUE TITLE
Version 2.7.3 in main anaconda label?

### ISSUE THREAD

**Issue by hadim** [conda-forge/libint-feedstock#21]
### Comment:

@loriab current psi4 still depends in this libint_dev label to get installed. It works well but it's not ideal and using the singla main label of c-f seems preferred. Is there a plan to fix the situation? Or is it unsolvable for now?

**Comment by timostrunk** [comment]
As far as I know this is still blocked by the merge of this PR https://github.com/evaleev/libint/pull/259

**Comment by loriab** [comment]
I agree the libint_dev is not ideal. I've broken off the minimal pieces from 259 that psi4/c-f actually need at runtime and proposed them as separate PRs (271 is the cumulative one I think) at the libint repo. If that can get merged and released, then I can update the main libint here and largely retire libint_dev label.

**Comment by loriab** [comment]
fwiw, all the pieces are now merged in upstream libint. only a tag is lacking to resolve this issue.
